"""
    This PyQT6 application analyzes the CSV file generated by the Arche website of the University of Lorraine. The
    purpose of this application is to retrieve the highest grades of students between class times. The user specifies
    the class schedule, opens the file to be analyzed by pressing the “OPEN” button, filters the students if desired,
    and finally presses the  “compute” button to retrieve the students' highest grades.

    References: https://arche.univ-lorraine.fr/

    Author: Christophe Mathé

    Release date: 12th December 2025
"""
# ==================================================================================================================== #
# PYTHON LIBRARIES
# ==================================================================================================================== #
import sys

from PyQt6.QtWidgets           import QMainWindow, QApplication, QLabel, QWidget, QHBoxLayout

# ==================================================================================================================== #
# PROJECT LIBRARIES
# ==================================================================================================================== #
from frame.tool_bar            import ToolBar
from frame.widget_file_content import WidgetFileContent
from frame.widget_query        import WidgetQuery
from frame.widget_result       import WidgetResult
from lib.csv_file_manager      import open_csv

# ==================================================================================================================== #
# MAIN FRAME
# ==================================================================================================================== #
class MainWindow(QMainWindow):
    """
        This is the main window of the application.

        There are only two commons variables:
            - self.data: DataFrame with the CSV content
            - self.widget_input_file: QLabel with the input file name

        Here a schema to describe widgets and layout:

        +---------------------------------------------+
        | WindowTitle                                 |
        |---------------------------------------------|
        | ToolBar                                     |
        |---------------------------------------------|
        | widget_main, layout_main                    |
        | +-------------------+ +-------------------+ |
        | | widget_query      | | widget_plot_info  | |
        | |                   | |                   | |
        | +-------------------+ +-------------------+ |
        +---------------------------------------------+
    """

    __version__ = '1.0.0'

    def __init__(self):

        super().__init__()

        # ------------------------------------------------------------------------------------------------------------ #
        # Commons variables
        # ------------------------------------------------------------------------------------------------------------ #

        # Widget that contains the input file name
        self.widget_input_file = QLabel('')

        # DataFrame with the CSV content
        self.data = None

        # ------------------------------------------------------------------------------------------------------------ #
        # Main widget variables
        # ------------------------------------------------------------------------------------------------------------ #

        # Set the main window title (top left of the application)
        self.setWindowTitle(f"Arche Analyser v{self.__version__}")

        # Main widget
        self.widget_main = QWidget()

        # Main layout
        self.layout_main = QHBoxLayout()

        # Set the layout of the main widget
        self.widget_main.setLayout(self.layout_main)

        # ------------------------------------------------------------------------------------------------------------ #
        # Main widget variables
        # ------------------------------------------------------------------------------------------------------------ #

        # Create an instance of WidgetQuery, which contains the class selector, schedule editor, student filter, and
        # the "Compute" button.
        self.widget_query = WidgetQuery()

        # Add the WidgetQuery instance to the main layout so it becomes visible in the UI.
        self.layout_main.addWidget(self.widget_query)

        # Connect the "Compute" button's clicked signal to a window pop-up that contains highest grades of student
        # The `lambda _:` captures the unused click event parameter.
        self.widget_query.button_compute.clicked.connect(lambda _: WidgetResult(parent=self).compute())

        # Create an instance of WidgetFileContent which contains the file name display, csv table display
        self.widget_plot_info = WidgetFileContent(parent=self)

        # Add the WidgetFileContent instance to the main layout so it becomes visible in the UI.
        self.layout_main.addWidget(self.widget_plot_info)

        # ------------------------------------------------------------------------------------------------------------ #
        # Tool bar
        # ------------------------------------------------------------------------------------------------------------ #
        # Create an instance of ToolBar, which contains action "OPEN"
        self.tool_bar = ToolBar()

        # Bound the action "OPEN" to the open_csv function
        self.tool_bar.on_triggered('OPEN', open_csv)

        # Add the ToolBar instance to the application
        self.addToolBar(self.tool_bar)

        # ------------------------------------------------------------------------------------------------------------ #
        # Display the application
        # ------------------------------------------------------------------------------------------------------------ #
        # Set the main widget of the application
        self.setCentralWidget(self.widget_main)

        # Display the application
        self.show()


if __name__ == '__main__':
    app = QApplication(sys.argv)

    window = MainWindow()

    app.exec()

    app.quit()
